<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Tapa;
use AppBundle\Form\TapaType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/management")
 */
class ManagementTapaController extends Controller
{
    /**
     * @Route("/new", name="newTapa")
     */
    public function newTapaAction(Request $request): Response
    {
        $tapa = new Tapa();

        $form = $this->createForm(TapaType::class, $tapa);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $tapaUpdated = $this->createTapaObj($tapa);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tapaUpdated);
            $entityManager->flush();

            return $this->redirectToRoute('detail', [
                "id" => $tapaUpdated->getId()
            ]);
        }

        return $this->render('managementTapa/new_tapa.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    private function createTapaObj(Tapa $tapa): Tapa
    {
        $tapa->setCreationDate(new \DateTime());
        /** @var File $file */
        $file = $tapa->getPicture();
        $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
        $file->move(
            $this->getParameter('tapasImg_dir'),
            $fileName
        );
        $tapa->setPicture($fileName);

        return $tapa;
    }

    private function generateUniqueFileName(): string
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps.
        return md5(uniqid());
    }
}
