<?php

namespace AppBundle\Repository;

/**
 * TapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTapasInPage($page = 1, $NUM_TAPAS = 3)
    {
        $page = ($page > 0) ? $page : 1;

        $query = $this->createQueryBuilder('t')
            ->where('t.top = 1')
            ->setFirstResult($NUM_TAPAS * ($page - 1))
            ->setMaxResults($NUM_TAPAS)
            ->orderBy('t.id', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findTotalNumberOfPages($NUM_TAPAS = 3)
    {
        $config = new \Doctrine\ORM\Configuration();
        $config->addCustomNumericFunction('Ceil', 'AppBundle\Query\Ceil');

        $pages = $this->getEntityManager()->createQuery("
            SELECT CEIL(COUNT(t.id) / :numTapas )
            FROM AppBundle:Tapa t
            WHERE t.top = 1
            ")
            ->setParameter('numTapas', $NUM_TAPAS)
            ->getResult()[0][1];

        /* THE SAME. */
        /*$pages = $this->createQueryBuilder('t')
            ->select("CEIL(count(t.id) / :numTapas"))
            ->where('t.top = 1')
            ->getQuery()
            ->setParameter('numTapas', $NUM_TAPAS)
            ->getResult()[0][1];*/

        return $pages;
    }

}
